name: sitimoufr
description: SI-TIMOU 119 Responder.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network
  http: ^0.13.4  
  connectivity_plus: ^2.3.5
  internet_connection_checker: ^0.0.1+4
  url_launcher: ^6.1.5

  # State Management
  get: ^4.6.5

  # Maps  
  google_maps_flutter: ^2.1.12
  # geolocator: ^9.0.1 
  # geocoding: ^2.0.5

  # Notification
  firebase_core: ^1.21.0
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1

  # UI
  animated_widgets: ^1.1.0
  double_back_to_close_app: ^2.1.0
  sleek_button: ^0.2.0  
  fluentui_system_icons: ^1.1.172  
  liquid_pull_to_refresh: ^3.0.1    
  cool_alert: ^1.1.0
  # flutter_datetime_picker: ^1.5.1
  # animated_bottom_navigation_bar: ^1.1.0
  # holding_gesture: ^1.1.0
  # avatar_glow: ^2.0.2
  # dropdown_button2: ^1.8.0

  # Image & Camera
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3

  # Storage  
  # file_picker: ^5.0.1
  file_picker: ^5.2.0+1
  flutter_secure_storage: ^5.0.2
  path_provider: ^2.0.11

  # Others  
  # flutter_phoenix: ^1.1.0
  flutter_html: ^3.0.0-alpha.5
  permission_handler: ^10.0.0    
  cupertino_icons: ^1.0.2
  intl: ^0.17.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:    
    - assets/images/
    - assets/images/gif/
    - assets/images/logo/    
    - assets/images/gif/loading.gif    
    - assets/lottie/
    - assets/images/icon/user.png
  
  fonts:
    - family: Haettenschweiler
      fonts:
        - asset: assets/fonts/Haettenschweiler-Regular.ttf

  
